# Generated by Django 5.1.3 on 2024-11-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='jpravi',
        ),
    ]
