# Generated by Django 5.1.3 on 2024-11-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_rename_person_jpravi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jpravi',
            new_name='Person',
        ),
    ]
